Import ('env')

name = 'mili'
inc = env.Dir('.')
src = env.Glob('*.cpp')
deps = ['mili','gmock','gtest_main', 'gtest']
CXXFLAGS = ['-Wall', '-Wextra', '-Wno-sign-compare', '-ggdb3']

env.Replace(CXXFLAGS=CXXFLAGS, CFLAGS=CXXFLAGS)
env.CreateTest(name, inc, src, deps)
