Import ('env')

name = 'mili'
inc = env.Dir('.')
src = env.Glob('*.cpp')
deps = ['mili','gmock','gtest_main']

env.CreateTest(name, inc, src, deps, CXXFLAGS = ['-Wall', '-Wextra', '-Wno-sign-compare'])
